---
- hosts: local 
  become: yes
  vars:
    adauth_realm: "HOME.LOCAL"
    adauth_pdc: "danidc1.home.local"
  tasks:

    - name: Install Prereq software for Windows communication
      yum: state=present name='python-devel, krb5-devel, krb5-libs, krb5-workstation, python2-winrm'

    - name: set /etc/krb5.conf
      template: src=krb5.conf dest=/etc/krb5.conf owner=root group=root mode=644
