---
- hosts: cent
  become: yes
  
  tasks:
    - name: Update Systems through yum
      yum: name=* state=latest update_cache=true
      when: ansible_os_family == "RedHat"
    - name: Update Systems through apt
      apt:  state=latest update_cache=yes
      when: ansible_os_family == "Debian"
